apiVersion: v1
kind: Service
metadata:
  name: flowlet-web-frontend-service
  labels:
    app: flowlet
    tier: web-frontend
spec:
  selector:
    app: flowlet
    tier: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
