apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowlet.fullname" . }}-web-frontend
  labels:
    {{- include "flowlet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-frontend
spec:
  type: {{ .Values.web-frontend.service.type }}
  ports:
    - port: {{ .Values.web-frontend.service.port }}
      targetPort: {{ .Values.web-frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "flowlet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-frontend
